name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm run build
          cd dist
          git init
          git add -A
          git commit -m 'deploy'
          git push -f git@github.com:Huauauaa/antv.git master:gh-pages
